[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
float_to_top = "true"
multi_line_output=3
include_trailing_comma="true"
line_length=88

[tool.black]
line-length = 88
